### ISSUE TITLE
Usage for toolbox

### ISSUE THREAD

**Issue by VarLad** [void-linux/void-docker#18]
Hey! We wish make toolbox containers based on the images (at https://github.com/toolbx-images/images )
- Is it okay to use this repo as reference?
- If we have someone to maintain the toolbox images, would someone from this repo mind assisting with making the images for toolbox?

**Comment by classabbyamp** [comment]
> * Is it okay to use this repo as reference?

it's [BSD2](https://github.com/void-linux/void-containers/blob/master/COPYING), so sure.

> * If we have someone to maintain the toolbox images, would someone from this repo mind assisting with making the images for toolbox?

I could maybe take a look over them
