### ISSUE TITLE
busybox images fail cert verification on xbps sync

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-docker#2]
the following tags:
- latest-mini-bb-x86_64
- latest-mini-bb-x86_64-musl
- latest-thin-bb-x86_64
- latest-thin-bb-x86_64-musl

all fail with the same cert verification failure.

### Minimal Example

```dockerfile
FROM ghcr.io/void-linux/void-linux:latest-mini-bb-x86_64

RUN xbps-install -SuyM

CMD ["/bin/sh"]
```

#### Output

```
$ docker build .
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM ghcr.io/void-linux/void-linux:latest-mini-bb-x86_64
 ---> d912037f4d51
Step 2/3 : RUN xbps-install -SuyM
 ---> Running in 7b5dd0aa8f57
Certificate verification failed for /C=US/O=Internet Security Research Group/CN=ISRG Root X1
SSL_connect returned 1
ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata': Operation not permitted
Certificate verification failed for /C=US/O=Internet Security Research Group/CN=ISRG Root X1
SSL_connect returned 1
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
The command '/bin/sh -c xbps-install -SuyM' returned a non-zero code: 95
```

Does not happen if the `latest-mini-x86_64` tag is used:

```
docker build .
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM ghcr.io/void-linux/void-linux:latest-mini-x86_64
 ---> 2cbb9bf2e855
Step 2/3 : RUN xbps-install -SuyM
 ---> Running in 0a71a9a6c39a
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
x86_64-repodata: [1701KB 0%] 217MB/s ETA: 00m00s
x86_64-repodata: [1701KB 70%] 1290KB/s ETA: 00m00s
x86_64-repodata: 1701KB [avg rate: 1828KB/s]

...

Removing intermediate container 0a71a9a6c39a
 ---> 00aa26ad69ad
Step 3/3 : CMD ["/bin/sh"]
 ---> Running in 29ead3a54b7c
Removing intermediate container 29ead3a54b7c
 ---> 3f99e4de5e62
Successfully built 3f99e4de5e62

**Comment by mibere** [comment]
The command (with repository _repo-us.voidlinux.org_ and _alpha.de.repo.voidlinux.org_)

```
RUN XBPS_ARCH=armv7l xbps-install -yMU --repository=https://repo-us.voidlinux.org/current --repository=https://repo-us.voidlinux.org/current/musl -r /target xbps base-files dash coreutils grep run-parts sed gawk
```

also aborts with

```
Certificate verification failed for /C=US/O=Internet Security Research Group/CN=ISRG Root X1
SSL_connect returned 1
```

It's reproducible with [Dockerfile.bootstrap](https://github.com/void-linux/void-docker/blob/master/Dockerfile.bootstrap) + [Dockerfile.mini](https://github.com/void-linux/void-docker/blob/master/Dockerfile.mini)

**Comment by the-maldridge** [comment]
The bootstrap issue appears to be resolved and was very likely a result of the X3 expiry.  We're actively debugging the issue with the `bb` images, and it appears to be a problem related to the busybox flavor itself.

**Comment by the-maldridge** [comment]
Alright, we've tracked this down to a GNU-ism with update-ca-certificates.  The certificates are present, but they aren't installed due to the script bailing out with an error.  A patch is in review for update-ca-certificates and we'll do a test after that patch goes through to see if everything is fine before rebuilding.

**Comment by dkwo** [comment]
After this is fixed, would it be possible to update the docker hub images, which currently have the same issue?
Specifically, voidlinux/masterdir-x86_64-musl TAG 20200607RC01
See https://trac.sagemath.org/ticket/33084#comment:4

**Comment by classabbyamp** [comment]
iirc the docker hub images will no longer be updated, and you should switch to the ghcr images

**Comment by classabbyamp** [comment]
tested again and seems to be fixed now.
