### ISSUE TITLE
Help debugging xbps issue when emulating amd64 on Apple Silicon?

### ISSUE THREAD

**Issue by ctjlewis** [void-linux/void-docker#21]
Hey, we have no issues running in amd64 environments, but on Apple Silicon trying to build with `--platform linux/amd64` and/or `FROM --platform linux/amd64 ghcr.io/void-linux/void-glibc-full:latest` gives us package manager issues:

```
 => CACHED [1/5] FROM ghcr.io/void-linux/void-glibc-full:latest@sha256:7f582c504050231708e55e10de0fd816c9f2dac721  0.0s
 => ERROR [2/5] RUN xbps-install -Syu &&     xbps-install -y curl tar xz                                           1.6s
------                                                                                                                  
 > [2/5] RUN xbps-install -Syu &&     xbps-install -y curl tar xz:                                                      
1.558 ERROR: [reposync] failed to fetch file `https://repo-default.voidlinux.org/current/x86_64-repodata': Requested Range Not Satisfiable
1.566 [*] Updating repository `https://repo-default.voidlinux.org/current/x86_64-repodata' ...
```

Any idea on how to work around this locally? Apologies if this should be more obvious, tried a few different things. Works fine in CI though!

**Comment by classabbyamp** [comment]
docker needs qemu-user-static + binfmt-support to run non-native platform containers, but it seems to be running the container fine. not sure what the issue with fetching is. does a native (linux/arm64) container work?

**Comment by Duncaen** [comment]
This error is HTTP `416` return code from the server, debug/verbose logs would be useful.

**Comment by classabbyamp** [comment]
If you have more information, this can be reopened
