### ISSUE TITLE
Container fails to start using Distrobox on Linux Mint 21.3

### ISSUE THREAD

**Issue by ghost** [void-linux/void-docker#22]
Distrobox is unable to start a void container on Linux Mint 21.3.  It was working fine a few weeks ago, and nothing else in my host system has changed.

Steps to reproduce:

Run 
```
distrobox create -i ghcr.io/void-linux/void-glibc-full -n void
Image ghcr.io/void-linux/void-glibc-full not found.
Do you want to pull the image now? [Y/n]: y
Trying to pull ghcr.io/void-linux/void-glibc-full:latest...
Getting image source signatures
Copying blob 5b5f5f05ee94 skipped: already exists  
Copying blob 1fc573451507 done  
Copying config 40ebd91a5a done  
Writing manifest to image destination
Storing signatures
40ebd91a5adb0c8cd2124fc7fbe91bc14dd9e8c7ff4ce92b78943258ea311bc6
Creating 'void' using image ghcr.io/void-linux/void-glibc-full	 [ OK ]
Distrobox 'void' successfully created.
To enter, run:

distrobox enter void

```
Then run
```
distrobox enter void
Starting container...                   	 [ OK ]
Installing basic packages...            	 Error: An error occurred
```

I get the exact same result from using void-glibc, void-musl, or void-musl-full instead.

**Comment by classabbyamp** [comment]
distrobox's scripts are probably broken, you'll have to ask them for support. unless you can get something more than distrobox saying "an error occurred", closing this

**Comment by dnkmmr69420** [comment]
I am getting the same issue

**Comment by classabbyamp** [comment]
well, provide a proper log with error and/or report it to distrobox...

**Comment by classabbyamp** [comment]
https://github.com/89luca89/distrobox/issues/1457 this is not a void issue but distrobox using xbps incorrectly
