### ISSUE TITLE
mini-bb-musl tag does not support linux/arm64/v8

### ISSUE THREAD

**Issue by sainnhe** [void-linux/void-docker#9]
```shell
$ sudo docker run -it --rm ghcr.io/void-linux/void-linux:mini-bb-musl
Unable to find image 'ghcr.io/void-linux/void-linux:mini-bb-musl' locally
mini-bb-musl: Pulling from void-linux/void-linux
b8bade5013d9: Pull complete
e5991dee9f7c: Pull complete
Digest: sha256:8ec89c31ad2e377e1a126c5f07f8d3cea88a9c432fde2098f0d7abbef3c16d17
Status: Downloaded newer image for ghcr.io/void-linux/void-linux:mini-bb-musl
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /bin/sh: exec format error
```

**Comment by classabbyamp** [comment]
use the `latest-mini-bb-aarch64-musl` tag

**Comment by sainnhe** [comment]
Why does a tag name contains architecture? Shouldn't all architectures use the same tag and let the OS decide which architecture to use?

**Comment by sainnhe** [comment]
https://github.com/void-linux/void-docker/blob/19905c48c1996ad598a80658215154f896cba479/.github/workflows/containers.yml#L58

IMO this line should build `linux/arm64` for the `mini-bb-musl` tag, so why it doesn't exist on ghcr registry? Is this a bug?

**Comment by classabbyamp** [comment]
looks like it is https://github.com/docker/build-push-action/issues/755
